from django.conf.urls import url, patterns
from . import views

app_name = 'vardata'

urlpatterns = [
    url(r'^$', views.index, name='vardata_prefix'),
    url(r'^MimicBcForm/$', views.MimicBc_1up),
    url(r'^MimicBcForm/(?P<ordereditem_id>\d+)/$', views.MimicBc_print),
    url(r'^TlaBcForm/$', views.TlaBc_1up),
    url(r'^TlaBcForm/(?P<ordereditem_id>\d+)/$', views.TlaBc_print),
    url(r'^HarrisCertificateForm/$', views.HarrisCertificate_1up),
    url(r'^HarrisCertificateForm/(?P<ordereditem_id>\d+)/$', views.HarrisCertificate_print),
    url(r'^DrAsiaPacificBcForm/$', views.DrAsiaPacificBc_1up),
    url(r'^DrAsiaPacificBcForm/(?P<ordereditem_id>\d+)/$', views.DrAsiaPacificBc_print),
    url(r'^DrMarkhamBcForm/$', views.DrMarkhamBc_1up),
    url(r'^DrMarkhamBcForm/(?P<ordereditem_id>\d+)/$', views.DrMarkhamBc_print),
    url(r'^DrUkBcForm/$', views.DrUkBc_1up),
    url(r'^DrUkBcForm/(?P<ordereditem_id>\d+)/$', views.DrUkBc_print),
    url(r'^DrRemoteBcForm/$', views.DrRemoteBc_1up),
    url(r'^DrRemoteBcForm/(?P<ordereditem_id>\d+)/$', views.DrRemoteBc_print),
    url(r'^CaTechTorontoBcForm/$', views.CaTechTorontoBc_1up),
    url(r'^CaTechTorontoBcForm/(?P<ordereditem_id>\d+)/$', views.CaTechTorontoBc_print),
    url(r'^CaTechMontrealBcForm/$', views.CaTechMontrealBc_1up),
    url(r'^CaTechMontrealBcForm/(?P<ordereditem_id>\d+)/$', views.CaTechMontrealBc_print),
    url(r'^CaTechOttawaBcForm/$', views.CaTechOttawaBc_1up),
    url(r'^CaTechOttawaBcForm/(?P<ordereditem_id>\d+)/$', views.CaTechOttawaBc_print),
    url(r'^CaTechBcForm/$', views.CaTechBc_1up),
    url(r'^CaTechBcForm/(?P<ordereditem_id>\d+)/$', views.CaTechBc_print),
    url(r'^RossBcForm/$', views.RossBc_1up),
    url(r'^RossBcForm/(?P<ordereditem_id>\d+)/$', views.RossBc_print),
    url(r'^TrilliumBcForm/$', views.TrilliumBc_1up),
    url(r'^TrilliumBcForm/(?P<ordereditem_id>\d+)/$', views.TrilliumBc_print),
    url(r'^KafkoEnglishCanadaBcForm/$', views.KafkoEnglishCanadaBc_1up),
    url(r'^KafkoEnglishCanadaBcForm/(?P<ordereditem_id>\d+)/$', views.KafkoEnglishCanadaBc_print),
    url(r'^KafkoFrenchCanadaBcForm/$', views.KafkoFrenchCanadaBc_1up),
    url(r'^KafkoFrenchCanadaBcForm/(?P<ordereditem_id>\d+)/$', views.KafkoFrenchCanadaBc_print),
    url(r'^KafkoUsBcForm/$', views.KafkoUsBc_1up),
    url(r'^KafkoUsBcForm/(?P<ordereditem_id>\d+)/$', views.KafkoUsBc_print),
    url(r'^AlgonquinMississaugaBcForm/$', views.AlgonquinMississaugaBc_1up),
    url(r'^AlgonquinMississaugaBcForm/(?P<ordereditem_id>\d+)/$', views.AlgonquinMississaugaBc_print),
    url(r'^AlgonquinOttawaBcForm/$', views.AlgonquinOttawaBc_1up),
    url(r'^AlgonquinOttawaBcForm/(?P<ordereditem_id>\d+)/$', views.AlgonquinOttawaBc_print),
    url(r'^SuperiorEnergyBcForm/$', views.SuperiorEnergyBc_1up),
    url(r'^SuperiorEnergyBcForm/(?P<ordereditem_id>\d+)/$', views.SuperiorEnergyBc_print),
    url(r'^SuperiorEnergyAgentBcForm/$', views.SuperiorEnergyAgentBc_1up),
    url(r'^SuperiorEnergyAgentBcForm/(?P<ordereditem_id>\d+)/$', views.SuperiorEnergyAgentBc_print),
    url(r'^RexallBcForm/$', views.RexallBc_1up),
    url(r'^RexallBcForm/(?P<ordereditem_id>\d+)/$', views.RexallBc_print),
    url(r'^EverestN10EnvelopeForm/$', views.EverestN10Envelope_1up),
    url(r'^EverestN10EnvelopeForm/(?P<ordereditem_id>\d+)/$', views.EverestN10Envelope_print),
    url(r'^Everest10x13EnvelopeForm/$', views.Everest10x13Envelope_1up),
    url(r'^Everest10x13EnvelopeForm/(?P<ordereditem_id>\d+)/$', views.Everest10x13Envelope_print),
    url(r'^Everest9x12EnvelopeForm/$', views.Everest9x12Envelope_1up),
    url(r'^Everest9x12EnvelopeForm/(?P<ordereditem_id>\d+)/$', views.Everest9x12Envelope_print),
    url(r'^Everest6x9EnvelopeForm/$', views.Everest6x9Envelope_1up),
    url(r'^Everest6x9EnvelopeForm/(?P<ordereditem_id>\d+)/$', views.Everest6x9Envelope_print),
    url(r'^EverestSampleLetterheadForm/$', views.EverestSampleLetterhead_1up),
    url(r'^EverestBCForm/$', views.EverestBC_1up),
    url(r'^EverestBCForm/(?P<ordereditem_id>\d+)/$', views.EverestBC_print),
    url(r'^TrilliumDoubleBCForm/$', views.TrilliumDoubleBC_1up),
    url(r'^TrilliumDoubleBCForm/(?P<ordereditem_id>\d+)/$', views.TrilliumDoubleBC_print),

]
