from django.conf.urls import url, patterns
from . import views

app_name = 'vardata'

urlpatterns = [
    url(r'^$', views.index, name='vardata_prefix'),
    url(r'^MimicBcForm/$', 'MimicBc_1up'),
    url(r'^MimicBcForm/(?P<ordereditem_id>\d+)/$', 'MimicBc_print'),
    url(r'^TlaBcForm/$', 'TlaBc_1up'),
    url(r'^TlaBcForm/(?P<ordereditem_id>\d+)/$', 'TlaBc_print'),
    url(r'^HarrisCertificateForm/$', 'HarrisCertificate_1up'),
    url(r'^HarrisCertificateForm/(?P<ordereditem_id>\d+)/$', 'HarrisCertificate_print'),
    url(r'^DrAsiaPacificBcForm/$', 'DrAsiaPacificBc_1up'),
    url(r'^DrAsiaPacificBcForm/(?P<ordereditem_id>\d+)/$', 'DrAsiaPacificBc_print'),
    url(r'^DrMarkhamBcForm/$', 'DrMarkhamBc_1up'),
    url(r'^DrMarkhamBcForm/(?P<ordereditem_id>\d+)/$', 'DrMarkhamBc_print'),
    url(r'^DrUkBcForm/$', 'DrUkBc_1up'),
    url(r'^DrUkBcForm/(?P<ordereditem_id>\d+)/$', 'DrUkBc_print'),
    url(r'^DrRemoteBcForm/$', 'DrRemoteBc_1up'),
    url(r'^DrRemoteBcForm/(?P<ordereditem_id>\d+)/$', 'DrRemoteBc_print'),
    url(r'^CaTechTorontoBcForm/$', 'CaTechTorontoBc_1up'),
    url(r'^CaTechTorontoBcForm/(?P<ordereditem_id>\d+)/$', 'CaTechTorontoBc_print'),
    url(r'^CaTechMontrealBcForm/$', 'CaTechMontrealBc_1up'),
    url(r'^CaTechMontrealBcForm/(?P<ordereditem_id>\d+)/$', 'CaTechMontrealBc_print'),
    url(r'^CaTechOttawaBcForm/$', 'CaTechOttawaBc_1up'),
    url(r'^CaTechOttawaBcForm/(?P<ordereditem_id>\d+)/$', 'CaTechOttawaBc_print'),
    url(r'^CaTechBcForm/$', 'CaTechBc_1up'),
    url(r'^CaTechBcForm/(?P<ordereditem_id>\d+)/$', 'CaTechBc_print'),
    url(r'^RossBcForm/$', 'RossBc_1up'),
    url(r'^RossBcForm/(?P<ordereditem_id>\d+)/$', 'RossBc_print'),
    url(r'^TrilliumBcForm/$', 'TrilliumBc_1up'),
    url(r'^TrilliumBcForm/(?P<ordereditem_id>\d+)/$', 'TrilliumBc_print'),
    url(r'^KafkoEnglishCanadaBcForm/$', 'KafkoEnglishCanadaBc_1up'),
    url(r'^KafkoEnglishCanadaBcForm/(?P<ordereditem_id>\d+)/$', 'KafkoEnglishCanadaBc_print'),
    url(r'^KafkoFrenchCanadaBcForm/$', 'KafkoFrenchCanadaBc_1up'),
    url(r'^KafkoFrenchCanadaBcForm/(?P<ordereditem_id>\d+)/$', 'KafkoFrenchCanadaBc_print'),
    url(r'^KafkoUsBcForm/$', 'KafkoUsBc_1up'),
    url(r'^KafkoUsBcForm/(?P<ordereditem_id>\d+)/$', 'KafkoUsBc_print'),
    url(r'^AlgonquinMississaugaBcForm/$', 'AlgonquinMississaugaBc_1up'),
    url(r'^AlgonquinMississaugaBcForm/(?P<ordereditem_id>\d+)/$', 'AlgonquinMississaugaBc_print'),
    url(r'^AlgonquinOttawaBcForm/$', 'AlgonquinOttawaBc_1up'),
    url(r'^AlgonquinOttawaBcForm/(?P<ordereditem_id>\d+)/$', 'AlgonquinOttawaBc_print'),
    url(r'^SuperiorEnergyBcForm/$', 'SuperiorEnergyBc_1up'),
    url(r'^SuperiorEnergyBcForm/(?P<ordereditem_id>\d+)/$', 'SuperiorEnergyBc_print'),
    url(r'^SuperiorEnergyAgentBcForm/$', 'SuperiorEnergyAgentBc_1up'),
    url(r'^SuperiorEnergyAgentBcForm/(?P<ordereditem_id>\d+)/$', 'SuperiorEnergyAgentBc_print'),
    url(r'^RexallBcForm/$', 'RexallBc_1up'),
    url(r'^RexallBcForm/(?P<ordereditem_id>\d+)/$', 'RexallBc_print'),
    url(r'^EverestN10EnvelopeForm/$', 'EverestN10Envelope_1up'),
    url(r'^EverestN10EnvelopeForm/(?P<ordereditem_id>\d+)/$', 'EverestN10Envelope_print'),
    url(r'^Everest10x13EnvelopeForm/$', 'Everest10x13Envelope_1up'),
    url(r'^Everest10x13EnvelopeForm/(?P<ordereditem_id>\d+)/$', 'Everest10x13Envelope_print'),
    url(r'^Everest9x12EnvelopeForm/$', 'Everest9x12Envelope_1up'),
    url(r'^Everest9x12EnvelopeForm/(?P<ordereditem_id>\d+)/$', 'Everest9x12Envelope_print'),
    url(r'^Everest6x9EnvelopeForm/$', 'Everest6x9Envelope_1up'),
    url(r'^Everest6x9EnvelopeForm/(?P<ordereditem_id>\d+)/$', 'Everest6x9Envelope_print'),
    url(r'^EverestSampleLetterheadForm/$', 'EverestSampleLetterhead_1up'),
    url(r'^EverestBCForm/$', 'EverestBC_1up'),
    url(r'^EverestBCForm/(?P<ordereditem_id>\d+)/$', 'EverestBC_print'),
    url(r'^TrilliumDoubleBCForm/$', 'TrilliumDoubleBC_1up'),
    url(r'^TrilliumDoubleBCForm/(?P<ordereditem_id>\d+)/$', 'TrilliumDoubleBC_print'),

]
