from django.conf.urls import url, patterns

urlpatterns = patterns('vardata.views',
    url(r'^$',
        view = 'index',
        name = 'vardata_prefix',
    ),
    (r'^MimicBcForm/$', 'MimicBc_1up'),
    (r'^MimicBcForm/(?P<ordereditem_id>\d+)/$', 'MimicBc_print'),
    (r'^TlaBcForm/$', 'TlaBc_1up'),
    (r'^TlaBcForm/(?P<ordereditem_id>\d+)/$', 'TlaBc_print'),
    (r'^HarrisCertificateForm/$', 'HarrisCertificate_1up'),
    (r'^HarrisCertificateForm/(?P<ordereditem_id>\d+)/$', 'HarrisCertificate_print'),
    (r'^DrAsiaPacificBcForm/$', 'DrAsiaPacificBc_1up'),
    (r'^DrAsiaPacificBcForm/(?P<ordereditem_id>\d+)/$', 'DrAsiaPacificBc_print'),
    (r'^DrMarkhamBcForm/$', 'DrMarkhamBc_1up'),
    (r'^DrMarkhamBcForm/(?P<ordereditem_id>\d+)/$', 'DrMarkhamBc_print'),
    (r'^DrUkBcForm/$', 'DrUkBc_1up'),
    (r'^DrUkBcForm/(?P<ordereditem_id>\d+)/$', 'DrUkBc_print'),
    (r'^DrRemoteBcForm/$', 'DrRemoteBc_1up'),
    (r'^DrRemoteBcForm/(?P<ordereditem_id>\d+)/$', 'DrRemoteBc_print'),
    (r'^CaTechTorontoBcForm/$', 'CaTechTorontoBc_1up'),
    (r'^CaTechTorontoBcForm/(?P<ordereditem_id>\d+)/$', 'CaTechTorontoBc_print'),
    (r'^CaTechMontrealBcForm/$', 'CaTechMontrealBc_1up'),
    (r'^CaTechMontrealBcForm/(?P<ordereditem_id>\d+)/$', 'CaTechMontrealBc_print'),
    (r'^CaTechOttawaBcForm/$', 'CaTechOttawaBc_1up'),
    (r'^CaTechOttawaBcForm/(?P<ordereditem_id>\d+)/$', 'CaTechOttawaBc_print'),
    (r'^CaTechBcForm/$', 'CaTechBc_1up'),
    (r'^CaTechBcForm/(?P<ordereditem_id>\d+)/$', 'CaTechBc_print'),
    (r'^RossBcForm/$', 'RossBc_1up'),
    (r'^RossBcForm/(?P<ordereditem_id>\d+)/$', 'RossBc_print'),
    (r'^TrilliumBcForm/$', 'TrilliumBc_1up'),
    (r'^TrilliumBcForm/(?P<ordereditem_id>\d+)/$', 'TrilliumBc_print'),
    (r'^KafkoEnglishCanadaBcForm/$', 'KafkoEnglishCanadaBc_1up'),
    (r'^KafkoEnglishCanadaBcForm/(?P<ordereditem_id>\d+)/$', 'KafkoEnglishCanadaBc_print'),
    (r'^KafkoFrenchCanadaBcForm/$', 'KafkoFrenchCanadaBc_1up'),
    (r'^KafkoFrenchCanadaBcForm/(?P<ordereditem_id>\d+)/$', 'KafkoFrenchCanadaBc_print'),
    (r'^KafkoUsBcForm/$', 'KafkoUsBc_1up'),
    (r'^KafkoUsBcForm/(?P<ordereditem_id>\d+)/$', 'KafkoUsBc_print'),
    (r'^AlgonquinMississaugaBcForm/$', 'AlgonquinMississaugaBc_1up'),
    (r'^AlgonquinMississaugaBcForm/(?P<ordereditem_id>\d+)/$', 'AlgonquinMississaugaBc_print'),
    (r'^AlgonquinOttawaBcForm/$', 'AlgonquinOttawaBc_1up'),
    (r'^AlgonquinOttawaBcForm/(?P<ordereditem_id>\d+)/$', 'AlgonquinOttawaBc_print'),
    (r'^SuperiorEnergyBcForm/$', 'SuperiorEnergyBc_1up'),
    (r'^SuperiorEnergyBcForm/(?P<ordereditem_id>\d+)/$', 'SuperiorEnergyBc_print'),
    (r'^SuperiorEnergyAgentBcForm/$', 'SuperiorEnergyAgentBc_1up'),
    (r'^SuperiorEnergyAgentBcForm/(?P<ordereditem_id>\d+)/$', 'SuperiorEnergyAgentBc_print'),
    (r'^RexallBcForm/$', 'RexallBc_1up'),
    (r'^RexallBcForm/(?P<ordereditem_id>\d+)/$', 'RexallBc_print'),
    (r'^EverestN10EnvelopeForm/$', 'EverestN10Envelope_1up'),
    (r'^EverestN10EnvelopeForm/(?P<ordereditem_id>\d+)/$', 'EverestN10Envelope_print'),
    (r'^Everest10x13EnvelopeForm/$', 'Everest10x13Envelope_1up'),
    (r'^Everest10x13EnvelopeForm/(?P<ordereditem_id>\d+)/$', 'Everest10x13Envelope_print'),
    (r'^Everest9x12EnvelopeForm/$', 'Everest9x12Envelope_1up'),
    (r'^Everest9x12EnvelopeForm/(?P<ordereditem_id>\d+)/$', 'Everest9x12Envelope_print'),
    (r'^Everest6x9EnvelopeForm/$', 'Everest6x9Envelope_1up'),
    (r'^Everest6x9EnvelopeForm/(?P<ordereditem_id>\d+)/$', 'Everest6x9Envelope_print'),
    (r'^EverestSampleLetterheadForm/$', 'EverestSampleLetterhead_1up'),
    (r'^EverestBCForm/$', 'EverestBC_1up'),
    (r'^EverestBCForm/(?P<ordereditem_id>\d+)/$', 'EverestBC_print'),
    (r'^TrilliumDoubleBCForm/$', 'TrilliumDoubleBC_1up'),
    (r'^TrilliumDoubleBCForm/(?P<ordereditem_id>\d+)/$', 'TrilliumDoubleBC_print'),

)
